// Texto esperado de cada entrada de las tablas traducidas (estado ES en
// prueba_textos_tablas.inc.c): ESPERADO(tabla, indice, "texto").
// Esta en UTF-8 como el codigo; el Makefile lo pasa a EUC-JP con el mismo
// conversor que el build, asi que la comparacion es byte a byte.

// Personajes: nombres propios, iguales en espanol
ESPERADO(dato_800E76A8, 0, "MARIO")
ESPERADO(dato_800E76A8, 1, "LUIGI")
ESPERADO(dato_800E76A8, 2, "YOSHI")
ESPERADO(dato_800E76A8, 3, "TOAD")
ESPERADO(dato_800E76A8, 4, "D.K.")
ESPERADO(dato_800E76A8, 5, "WARIO")
ESPERADO(dato_800E76A8, 6, "PEACH")
ESPERADO(dato_800E76A8, 7, "BOWSER")
ESPERADO(dato_800E76A8, 8, "ーーーー")

// Longitud de cada pista en metros
ESPERADO(longitudes_circuito, 0, "567m")
ESPERADO(longitudes_circuito, 1, "687m")
ESPERADO(longitudes_circuito, 2, "777m")
ESPERADO(longitudes_circuito, 3, "747m")
ESPERADO(longitudes_circuito, 4, "772m")
ESPERADO(longitudes_circuito, 5, "734m")
ESPERADO(longitudes_circuito, 6, "691m")
ESPERADO(longitudes_circuito, 7, "1025m")
ESPERADO(longitudes_circuito, 8, "717m")
ESPERADO(longitudes_circuito, 9, "527m")
ESPERADO(longitudes_circuito, 10, "1036m")
ESPERADO(longitudes_circuito, 11, "753m")
ESPERADO(longitudes_circuito, 12, "756m")
ESPERADO(longitudes_circuito, 13, "2000m")
ESPERADO(longitudes_circuito, 14, "1591m")
ESPERADO(longitudes_circuito, 15, "")
ESPERADO(longitudes_circuito, 16, "")
ESPERADO(longitudes_circuito, 17, "")
ESPERADO(longitudes_circuito, 18, "893m")
ESPERADO(longitudes_circuito, 19, "")

// Opciones
ESPERADO(menu_opcion_texto, 0, "VOLVER AL MENÚ PRINCIPAL")
ESPERADO(menu_opcion_texto, 1, "SONIDO")
ESPERADO(menu_opcion_texto, 2, "COPIAR FANTASMAS")
ESPERADO(menu_opcion_texto, 3, "BORRAR TODOS LOS DATOS")
ESPERADO(sonido_nombres_modo, 0, "ESTÉREO")
ESPERADO(sonido_nombres_modo, 1, "AURICULARES")
ESPERADO(sonido_nombres_modo, 2, "")
ESPERADO(sonido_nombres_modo, 3, "MONO")
ESPERADO(dato_800E7878, 0, "SE BORRARÁN TODOS LOS")
ESPERADO(dato_800E7878, 1, "DATOS PARA SIEMPRE.")
ESPERADO(dato_800E7878, 2, "¿QUIERES CONTINUAR?")
ESPERADO(dato_800E7884, 0, "")
ESPERADO(dato_800E7884, 1, "SE HAN BORRADO")
ESPERADO(dato_800E7884, 2, "TODOS LOS DATOS.")

// Datos de las pistas
ESPERADO(datos_menu_texto, 0, "CRUZ*VER DATOS  CUADRADO*SALIR")
ESPERADO(distancia_texto, 0, "LONGITUD")
ESPERADO(opcion_menu_texto, 0, "VOLVER AL MENÚ")
ESPERADO(opcion_menu_texto, 1, "BORRAR RÉCORDS DE LA PISTA")
ESPERADO(opcion_menu_texto, 2, "BORRAR FANTASMA DE LA PISTA")
ESPERADO(dato_800E7840, 0, "SALIR")
ESPERADO(dato_800E7840, 1, "BORRAR")
ESPERADO(borrar_mejor_fantasma_texto, 0, "SE BORRARÁN LOS RÉCORDS")
ESPERADO(borrar_mejor_fantasma_texto, 1, "Y LA MEJOR VUELTA DE")
ESPERADO(borrar_mejor_fantasma_texto, 2, "ESTA PISTA. ¿DE ACUERDO?")
ESPERADO(borrar_mejor_fantasma_texto, 3, "SE BORRARÁ EL FANTASMA")
ESPERADO(borrar_mejor_fantasma_texto, 4, "DE ESTA PISTA.")
ESPERADO(borrar_mejor_fantasma_texto, 5, "¿DE ACUERDO?")
ESPERADO(dato_800E7860, 0, "NO SE PUEDE BORRAR")
ESPERADO(dato_800E7860, 1, "EL FANTASMA")

// Copas y cilindradas (las entradas 5 a 8 repiten las copas, como en la N64)
ESPERADO(nombres_copa, 0, "COPA CHAMPIÑÓN")
ESPERADO(nombres_copa, 1, "COPA FLOR")
ESPERADO(nombres_copa, 2, "COPA ESTRELLA")
ESPERADO(nombres_copa, 3, "COPA ESPECIAL")
ESPERADO(nombres_copa, 4, "BATALLA")
ESPERADO(nombres_copa, 5, "COPA CHAMPIÑÓN")
ESPERADO(nombres_copa, 6, "COPA FLOR")
ESPERADO(nombres_copa, 7, "COPA ESTRELLA")
ESPERADO(nombres_copa, 8, "COPA ESPECIAL")
ESPERADO(texto_copa, 0, "NINGUNA")
ESPERADO(texto_copa, 1, "BRONCE")
ESPERADO(texto_copa, 2, "PLATA")
ESPERADO(texto_copa, 3, "ORO")
ESPERADO(dato_800E76CC, 0, "50(")
ESPERADO(dato_800E76CC, 1, "100(")
ESPERADO(dato_800E76CC, 2, "150(")
ESPERADO(dato_800E76CC, 3, "EXTRA")
ESPERADO(dato_800E76DC, 0, "50(")
ESPERADO(dato_800E76DC, 1, "100(")
ESPERADO(dato_800E76DC, 2, "150(")
ESPERADO(dato_800E76DC, 3, "EXTRA")

// Pausa, tiempos y resultados
ESPERADO(boton_pausa_texto, 0, "CONTINUAR")
ESPERADO(boton_pausa_texto, 1, "REINTENTAR")
ESPERADO(boton_pausa_texto, 2, "CAMBIAR PISTA")
ESPERADO(boton_pausa_texto, 3, "CAMBIAR PILOTO")
ESPERADO(boton_pausa_texto, 4, "SALIR")
ESPERADO(boton_pausa_texto, 5, "REPETICIÓN")
ESPERADO(boton_pausa_texto, 6, "GRABAR FANTASMA")
ESPERADO(texto_perder_victoria, 0, "¡VICTORIA!")
ESPERADO(texto_perder_victoria, 1, "¡DERROTA!")
ESPERADO(texto_tiempo_mejor, 0, "RÉCORDS")
ESPERADO(texto_tiempo_mejor, 1, "MEJOR VUELTA")
ESPERADO(texto_tiempo_vuelta, 0, "TIEMPOS DE VUELTA")
ESPERADO(texto_tiempo_prefijo, 0, "VUELTA 1")
ESPERADO(texto_tiempo_prefijo, 1, "VUELTA 2")
ESPERADO(texto_tiempo_prefijo, 2, "VUELTA 3")
ESPERADO(texto_tiempo_prefijo, 3, "TOTAL")
ESPERADO(dato_800E7744, 0, "1.º")
ESPERADO(dato_800E7744, 1, "2.º")
ESPERADO(dato_800E7744, 2, "3.º")
ESPERADO(dato_800E7744, 3, "4.º")
ESPERADO(dato_800E7744, 4, "5.º")
ESPERADO(dato_800E7744, 5, " ")
ESPERADO(dato_800E7778, 0, "CLASIFICACIÓN VS")
ESPERADO(dato_800E7778, 1, "CLASIFICACIÓN BATALLA")
ESPERADO(texto_resultados, 0, "RESULTADOS")
ESPERADO(texto_ronda, 0, "RONDA")
ESPERADO(texto_puntos_piloto, 0, "CLASIFICACIÓN")
ESPERADO(texto_puesto_versus, 0, "1.º ー")
ESPERADO(texto_puesto_versus, 1, "2.º ー")
ESPERADO(texto_puesto_versus, 2, "3.º ー")
