// Texto esperado de cada entrada de las tablas traducidas (estado ES en
// prueba_textos_tablas.inc.c): ESPERADO(tabla, indice, "texto").
// Esta en UTF-8 como el codigo; el Makefile lo pasa a EUC-JP con el mismo
// conversor que el build, asi que la comparacion es byte a byte.

// Personajes: nombres propios, iguales en espanol
ESPERADO(dato_800E76A8, 0, "MARIO")
ESPERADO(dato_800E76A8, 1, "LUIGI")
ESPERADO(dato_800E76A8, 2, "YOSHI")
ESPERADO(dato_800E76A8, 3, "TOAD")
ESPERADO(dato_800E76A8, 4, "D.K.")
ESPERADO(dato_800E76A8, 5, "WARIO")
ESPERADO(dato_800E76A8, 6, "PEACH")
ESPERADO(dato_800E76A8, 7, "BOWSER")
ESPERADO(dato_800E76A8, 8, "ーーーー")

// Longitud de cada pista en metros
ESPERADO(longitudes_circuito, 0, "567m")
ESPERADO(longitudes_circuito, 1, "687m")
ESPERADO(longitudes_circuito, 2, "777m")
ESPERADO(longitudes_circuito, 3, "747m")
ESPERADO(longitudes_circuito, 4, "772m")
ESPERADO(longitudes_circuito, 5, "734m")
ESPERADO(longitudes_circuito, 6, "691m")
ESPERADO(longitudes_circuito, 7, "1025m")
ESPERADO(longitudes_circuito, 8, "717m")
ESPERADO(longitudes_circuito, 9, "527m")
ESPERADO(longitudes_circuito, 10, "1036m")
ESPERADO(longitudes_circuito, 11, "753m")
ESPERADO(longitudes_circuito, 12, "756m")
ESPERADO(longitudes_circuito, 13, "2000m")
ESPERADO(longitudes_circuito, 14, "1591m")
ESPERADO(longitudes_circuito, 15, "")
ESPERADO(longitudes_circuito, 16, "")
ESPERADO(longitudes_circuito, 17, "")
ESPERADO(longitudes_circuito, 18, "893m")
ESPERADO(longitudes_circuito, 19, "")

// Opciones
ESPERADO(menu_opcion_texto, 0, "VOLVER AL MENÚ PRINCIPAL")
ESPERADO(menu_opcion_texto, 1, "SONIDO")
ESPERADO(menu_opcion_texto, 2, "COPIAR FANTASMAS")
ESPERADO(menu_opcion_texto, 3, "BORRAR TODOS LOS DATOS")
ESPERADO(sonido_nombres_modo, 0, "ESTÉREO")
ESPERADO(sonido_nombres_modo, 1, "AURICULARES")
ESPERADO(sonido_nombres_modo, 2, "")
ESPERADO(sonido_nombres_modo, 3, "MONO")
ESPERADO(dato_800E7878, 0, "SE BORRARÁN TODOS LOS")
ESPERADO(dato_800E7878, 1, "DATOS PARA SIEMPRE.")
ESPERADO(dato_800E7878, 2, "¿QUIERES CONTINUAR?")
ESPERADO(dato_800E7884, 0, "")
ESPERADO(dato_800E7884, 1, "SE HAN BORRADO")
ESPERADO(dato_800E7884, 2, "TODOS LOS DATOS.")

// Datos de las pistas
ESPERADO(datos_menu_texto, 0, "CRUZ*VER DATOS  CUADRADO*SALIR")
ESPERADO(distancia_texto, 0, "LONGITUD")
ESPERADO(opcion_menu_texto, 0, "VOLVER AL MENÚ")
ESPERADO(opcion_menu_texto, 1, "BORRAR RÉCORDS DE LA PISTA")
ESPERADO(opcion_menu_texto, 2, "BORRAR FANTASMA DE LA PISTA")
ESPERADO(dato_800E7840, 0, "SALIR")
ESPERADO(dato_800E7840, 1, "BORRAR")
ESPERADO(borrar_mejor_fantasma_texto, 0, "SE BORRARÁN LOS RÉCORDS")
ESPERADO(borrar_mejor_fantasma_texto, 1, "Y LA MEJOR VUELTA DE")
ESPERADO(borrar_mejor_fantasma_texto, 2, "ESTA PISTA. ¿DE ACUERDO?")
ESPERADO(borrar_mejor_fantasma_texto, 3, "SE BORRARÁ EL FANTASMA")
ESPERADO(borrar_mejor_fantasma_texto, 4, "DE ESTA PISTA.")
ESPERADO(borrar_mejor_fantasma_texto, 5, "¿DE ACUERDO?")
ESPERADO(dato_800E7860, 0, "NO SE PUEDE BORRAR")
ESPERADO(dato_800E7860, 1, "EL FANTASMA")

// Copas y cilindradas (las entradas 5 a 8 repiten las copas, como en la N64)
ESPERADO(nombres_copa, 0, "COPA CHAMPIÑÓN")
ESPERADO(nombres_copa, 1, "COPA FLOR")
ESPERADO(nombres_copa, 2, "COPA ESTRELLA")
ESPERADO(nombres_copa, 3, "COPA ESPECIAL")
ESPERADO(nombres_copa, 4, "BATALLA")
ESPERADO(nombres_copa, 5, "COPA CHAMPIÑÓN")
ESPERADO(nombres_copa, 6, "COPA FLOR")
ESPERADO(nombres_copa, 7, "COPA ESTRELLA")
ESPERADO(nombres_copa, 8, "COPA ESPECIAL")
ESPERADO(texto_copa, 0, "NINGUNA")
ESPERADO(texto_copa, 1, "BRONCE")
ESPERADO(texto_copa, 2, "PLATA")
ESPERADO(texto_copa, 3, "ORO")
ESPERADO(dato_800E76CC, 0, "50(")
ESPERADO(dato_800E76CC, 1, "100(")
ESPERADO(dato_800E76CC, 2, "150(")
ESPERADO(dato_800E76CC, 3, "EXTRA")
ESPERADO(dato_800E76DC, 0, "50(")
ESPERADO(dato_800E76DC, 1, "100(")
ESPERADO(dato_800E76DC, 2, "150(")
ESPERADO(dato_800E76DC, 3, "EXTRA")

// Pausa, tiempos y resultados
ESPERADO(boton_pausa_texto, 0, "CONTINUAR")
ESPERADO(boton_pausa_texto, 1, "REINTENTAR")
ESPERADO(boton_pausa_texto, 2, "CAMBIAR PISTA")
ESPERADO(boton_pausa_texto, 3, "CAMBIAR PILOTO")
ESPERADO(boton_pausa_texto, 4, "SALIR")
ESPERADO(boton_pausa_texto, 5, "REPETICIÓN")
ESPERADO(boton_pausa_texto, 6, "GRABAR FANTASMA")
ESPERADO(texto_perder_victoria, 0, "¡VICTORIA!")
ESPERADO(texto_perder_victoria, 1, "¡DERROTA!")
ESPERADO(texto_tiempo_mejor, 0, "RÉCORDS")
ESPERADO(texto_tiempo_mejor, 1, "MEJOR VUELTA")
ESPERADO(texto_tiempo_vuelta, 0, "TIEMPOS DE VUELTA")
ESPERADO(texto_tiempo_prefijo, 0, "VUELTA 1")
ESPERADO(texto_tiempo_prefijo, 1, "VUELTA 2")
ESPERADO(texto_tiempo_prefijo, 2, "VUELTA 3")
ESPERADO(texto_tiempo_prefijo, 3, "TOTAL")
ESPERADO(dato_800E7744, 0, "1.º")
ESPERADO(dato_800E7744, 1, "2.º")
ESPERADO(dato_800E7744, 2, "3.º")
ESPERADO(dato_800E7744, 3, "4.º")
ESPERADO(dato_800E7744, 4, "5.º")
ESPERADO(dato_800E7744, 5, " ")
ESPERADO(dato_800E7778, 0, "CLASIFICACIÓN VS")
ESPERADO(dato_800E7778, 1, "CLASIFICACIÓN BATALLA")
ESPERADO(texto_resultados, 0, "RESULTADOS")
ESPERADO(texto_ronda, 0, "RONDA")
ESPERADO(texto_puntos_piloto, 0, "CLASIFICACIÓN")
ESPERADO(texto_puesto_versus, 0, "1.º ー")
ESPERADO(texto_puesto_versus, 1, "2.º ー")
ESPERADO(texto_puesto_versus, 2, "3.º ー")

// Memory Card y fantasmas
ESPERADO(dato_800E7890, 0, "NO HAY MEMORY CARD")
ESPERADO(dato_800E7890, 1, "EN LA RANURA 1.")
ESPERADO(dato_800E7890, 2, "")
ESPERADO(dato_800E7890, 3, "")
ESPERADO(dato_800E7890, 4, "NO SE PUEDEN LEER")
ESPERADO(dato_800E7890, 5, "LOS DATOS DE LA")
ESPERADO(dato_800E7890, 6, "MEMORY CARD DE LA RANURA 1.")
ESPERADO(dato_800E7890, 7, "")
ESPERADO(dato_800E7890, 8, "NO SE PUEDEN CREAR LOS DATOS")
ESPERADO(dato_800E7890, 9, "DEL JUEGO EN LA")
ESPERADO(dato_800E7890, 10, "MEMORY CARD DE LA RANURA 1.")
ESPERADO(dato_800E7890, 11, "")
ESPERADO(dato_800E7890, 12, "NO SE PUDO COPIAR EL FANTASMA")
ESPERADO(dato_800E7890, 13, "-- NO HAY ESPACIO LIBRE")
ESPERADO(dato_800E7890, 14, "EN LA MEMORY CARD")
ESPERADO(dato_800E7890, 15, "DE LA RANURA 1.")
ESPERADO(dato_800E78D0, 0, "NO HAY FANTASMAS")
ESPERADO(dato_800E78D0, 1, "EN LA MEMORY CARD")
ESPERADO(dato_800E78D0, 2, "DE LA RANURA 2.")
ESPERADO(dato_800E78D0, 3, "LA MEMORY CARD DE LA")
ESPERADO(dato_800E78D0, 4, "RANURA 2 NO TIENE")
ESPERADO(dato_800E78D0, 5, "DATOS DE MARIO KART 64.")
ESPERADO(dato_800E78D0, 6, "COPIAR FANTASMAS DESDE")
ESPERADO(dato_800E78D0, 7, "OTRA MEMORY CARD NO")
ESPERADO(dato_800E78D0, 8, "ESTÁ DISPONIBLE EN PS2.")
ESPERADO(dato_800E78D0, 9, "NO SE PUEDEN LEER LOS")
ESPERADO(dato_800E78D0, 10, "DATOS DE LA MEMORY CARD")
ESPERADO(dato_800E78D0, 11, "DE LA RANURA 2.")
ESPERADO(dato_800E7900, 0, "NO SE PUEDEN COPIAR")
ESPERADO(dato_800E7900, 1, "LOS DATOS DE LA")
ESPERADO(dato_800E7900, 2, "RANURA 1.")
ESPERADO(dato_800E7900, 3, "NO SE PUEDEN LEER")
ESPERADO(dato_800E7900, 4, "LOS DATOS DE LA")
ESPERADO(dato_800E7900, 5, "RANURA 2.")
ESPERADO(dato_800E7918, 0, "RANURA 1")
ESPERADO(dato_800E7918, 1, "RANURA 2")
ESPERADO(dato_800E7920, 0, "¿QUÉ FANTASMA QUIERES COPIAR?")
ESPERADO(dato_800E7920, 1, "¿DÓNDE QUIERES COPIARLO?")
ESPERADO(dato_800E7928, 0, "SE BORRARÁN LOS DATOS ACTUALES.")
ESPERADO(dato_800E7928, 1, "¿DE ACUERDO?")
ESPERADO(dato_800E7930, 0, "SALIR")
ESPERADO(dato_800E7930, 1, "COPIAR")
ESPERADO(dato_800E7938, 0, "COPIANDO")
ESPERADO(dato_800E7938, 1, "COPIA TERMINADA")
ESPERADO(dato_800E7940, 0, "NO SE DETECTA LA MEMORY CARD")
ESPERADO(dato_800E7940, 1, "PARA GRABAR FANTASMAS,")
ESPERADO(dato_800E7940, 2, "INSERTA UNA MEMORY CARD")
ESPERADO(dato_800E7940, 3, "EN LA RANURA 1.")
ESPERADO(dato_800E7940, 4, "NO SE PUEDEN LEER LOS")
ESPERADO(dato_800E7940, 5, "DATOS DE LA MEMORY CARD.")
ESPERADO(dato_800E7940, 6, "")
ESPERADO(dato_800E7940, 7, "")
ESPERADO(dato_800E7940, 8, "")
ESPERADO(dato_800E7940, 9, "")
ESPERADO(dato_800E7940, 10, "")
ESPERADO(dato_800E7940, 11, "")
ESPERADO(dato_800E7940, 12, "NO HAY ESPACIO SUFICIENTE")
ESPERADO(dato_800E7940, 13, "EN LA MEMORY CARD PARA")
ESPERADO(dato_800E7940, 14, "CREAR LOS DATOS DEL JUEGO.")
ESPERADO(dato_800E7940, 15, "LIBERA ESPACIO Y PRUEBA DE NUEVO.")
ESPERADO(dato_800E7980, 0, "PARA GRABAR FANTASMAS,")
ESPERADO(dato_800E7980, 1, "INSERTA UNA MEMORY CARD")
ESPERADO(dato_800E7980, 2, "EN LA RANURA 1.")
ESPERADO(dato_800E798C, 0, "NO SE DETECTA")
ESPERADO(dato_800E798C, 1, "LA MEMORY CARD.")
ESPERADO(dato_800E798C, 2, "SI QUIERES GRABAR")
ESPERADO(dato_800E798C, 3, "EL FANTASMA,")
ESPERADO(dato_800E798C, 4, "INSERTA UNA")
ESPERADO(dato_800E798C, 5, "MEMORY CARD")
ESPERADO(dato_800E798C, 6, "EN LA RANURA 1.")
ESPERADO(dato_800E798C, 7, "")
ESPERADO(dato_800E798C, 8, "NO SE PUEDE GRABAR")
ESPERADO(dato_800E798C, 9, "     EL FANTASMA.")
ESPERADO(dato_800E798C, 10, "")
ESPERADO(dato_800E798C, 11, "")
ESPERADO(dato_800E798C, 12, "")
ESPERADO(dato_800E798C, 13, "")
ESPERADO(dato_800E798C, 14, "")
ESPERADO(dato_800E798C, 15, "NO SE PUEDE GRABAR")
ESPERADO(dato_800E798C, 16, "     EL FANTASMA.")
ESPERADO(dato_800E798C, 17, "")
ESPERADO(dato_800E798C, 18, "")
ESPERADO(dato_800E798C, 19, "")
ESPERADO(dato_800E798C, 20, "")
ESPERADO(dato_800E798C, 21, "NO HAY ESPACIO")
ESPERADO(dato_800E798C, 22, "LIBRE SUFICIENTE.")
ESPERADO(dato_800E798C, 23, "")
ESPERADO(dato_800E798C, 24, "-- NO SE PUDO")
ESPERADO(dato_800E798C, 25, "GRABAR EL FANTASMA.")
ESPERADO(dato_800E798C, 26, "")
ESPERADO(dato_800E798C, 27, "")
ESPERADO(dato_800E798C, 28, "")
ESPERADO(dato_800E798C, 29, "NO SE PUEDEN CREAR")
ESPERADO(dato_800E798C, 30, "     LOS DATOS.")
ESPERADO(dato_800E798C, 31, "")
ESPERADO(dato_800E798C, 32, "")
ESPERADO(dato_800E798C, 33, "")
ESPERADO(dato_800E798C, 34, "")
ESPERADO(dato_800E798C, 35, "")
ESPERADO(dato_800E798C, 36, "ESTE FANTASMA")
ESPERADO(dato_800E798C, 37, "     YA SE HA GRABADO.")
ESPERADO(dato_800E798C, 38, "")
ESPERADO(dato_800E798C, 39, "")
ESPERADO(dato_800E798C, 40, "")
ESPERADO(dato_800E798C, 41, "")
ESPERADO(dato_800E7A34, 0, "NO SE PUEDE GRABAR")
ESPERADO(dato_800E7A34, 1, "COMO FANTASMA.")
ESPERADO(dato_800E7A3C, 0, "ELIGE EL ARCHIVO")
ESPERADO(dato_800E7A3C, 1, "PARA GRABAR.")
ESPERADO(dato_800E7A44, 0, "SIN DATOS")
ESPERADO(dato_800E7A48, 0, "CREANDO LOS")
ESPERADO(dato_800E7A48, 1, "DATOS DE")
ESPERADO(dato_800E7A48, 2, "MARIO KART 64")
ESPERADO(dato_800E7A54, 0, "NO SE PUEDEN CREAR LOS DATOS")
ESPERADO(dato_800E7A54, 1, "")
ESPERADO(dato_800E7A54, 2, "")
ESPERADO(dato_800E7A60, 0, "SE BORRARÁN LOS")
ESPERADO(dato_800E7A60, 1, "DATOS ANTERIORES.")
ESPERADO(dato_800E7A60, 2, "¿DE ACUERDO?")
ESPERADO(dato_800E7A6C, 0, "SALIR")
ESPERADO(dato_800E7A6C, 1, "GRABAR")
ESPERADO(dato_800E7A74, 0, "GRABANDO")
ESPERADO(dato_800E7A74, 1, "EL FANTASMA.")
ESPERADO(dato_800E7A74, 2, "ESPERA, POR FAVOR")
ESPERADO(dato_800E7A80, 0, "NO SE GRABÓ")
ESPERADO(dato_800E7A80, 1, "EL FANTASMA.")

// Ceremonia
ESPERADO(dato_800E7A88, 0, "HAS GANADO LA")
ESPERADO(dato_800E7A88, 1, "COPA DE ORO")
ESPERADO(dato_800E7A88, 2, "COPA DE PLATA")
ESPERADO(dato_800E7A88, 3, "COPA DE BRONCE")
ESPERADO(dato_800E7A98, 0, "¡SUERTE LA PRÓXIMA VEZ!")
ESPERADO(dato_800E7A9C, 0, "¡FELICIDADES!")
ESPERADO(dato_800E7A9C, 1, "¡QUÉ PENA!")
ESPERADO(texto_lugar, 0, "HAS QUEDADO")
ESPERADO(texto_lugar, 1, "   .º")
ESPERADO(texto_lugar, 2, "   .º")
ESPERADO(texto_lugar, 3, "   .º")
ESPERADO(texto_lugar, 4, "   .º")
ESPERADO(texto_lugar, 5, "   .º")
ESPERADO(texto_lugar, 6, "   .º")
ESPERADO(texto_lugar, 7, "   .º")
ESPERADO(texto_lugar, 8, "   .º")

// Creditos: roles en espanol, nombres propios sin cambios (solo la parte que se dibuja)
ESPERADO(texto_creditos, 0, "producción ejecutiva")
ESPERADO(texto_creditos, 1, "hiroshi yamauchi")
ESPERADO(texto_creditos, 2, "producción")
ESPERADO(texto_creditos, 3, "shigeru miyamoto")
ESPERADO(texto_creditos, 4, "dirección")
ESPERADO(texto_creditos, 5, "hideki konno")
ESPERADO(texto_creditos, 6, "ayudante de dirección")
ESPERADO(texto_creditos, 7, "yasuyuki oyagi")
ESPERADO(texto_creditos, 8, "programación")
ESPERADO(texto_creditos, 9, "masato kimura")
ESPERADO(texto_creditos, 10, "kenji yamamoto")
ESPERADO(texto_creditos, 11, "yasuhiro kawaguchi")
ESPERADO(texto_creditos, 12, "yuzuru ogawa")
ESPERADO(texto_creditos, 13, "masahiro kawano")
ESPERADO(texto_creditos, 14, "hirohito yoshimoto")
ESPERADO(texto_creditos, 15, "programación de la demo")
ESPERADO(texto_creditos, 16, "")
ESPERADO(texto_creditos, 17, "hajime yajima")
ESPERADO(texto_creditos, 18, "takumi kawagoe")
ESPERADO(texto_creditos, 19, "dirección visual")
ESPERADO(texto_creditos, 20, "tadashi sugiyama")
ESPERADO(texto_creditos, 21, "diseño de personajes cg")
ESPERADO(texto_creditos, 22, "")
ESPERADO(texto_creditos, 23, "tomoaki kuroume")
ESPERADO(texto_creditos, 24, "hiroaki takenaka")
ESPERADO(texto_creditos, 25, "tokihiko toyoda")
ESPERADO(texto_creditos, 26, "shigefumi hino")
ESPERADO(texto_creditos, 27, "masanao arimoto")
ESPERADO(texto_creditos, 28, "hisashi nogami")
ESPERADO(texto_creditos, 29, "diseño de circuitos cg")
ESPERADO(texto_creditos, 30, "makoto miyanaga")
ESPERADO(texto_creditos, 31, "naoki mori")
ESPERADO(texto_creditos, 32, "hiroyasu kuwabara")
ESPERADO(texto_creditos, 33, "composición musical")
ESPERADO(texto_creditos, 34, "kenta nagata")
ESPERADO(texto_creditos, 35, "programación de sonido")
ESPERADO(texto_creditos, 36, "taro bando")
ESPERADO(texto_creditos, 37, "yoji inagaki")
ESPERADO(texto_creditos, 38, "voces")
ESPERADO(texto_creditos, 39, "charles martinet")
ESPERADO(texto_creditos, 40, "leslie swan")
ESPERADO(texto_creditos, 41, "isaac marshall")
ESPERADO(texto_creditos, 42, "")
ESPERADO(texto_creditos, 43, "")
ESPERADO(texto_creditos, 44, "")
ESPERADO(texto_creditos, 45, "soporte técnico")
ESPERADO(texto_creditos, 46, "takao sawano")
ESPERADO(texto_creditos, 47, "tsuyoshi takahashi")
ESPERADO(texto_creditos, 48, "hirohito yada")
ESPERADO(texto_creditos, 49, "coordinación del proyecto")
ESPERADO(texto_creditos, 50, "kimiyoshi fukui")
ESPERADO(texto_creditos, 51, "keizo kato")
ESPERADO(texto_creditos, 52, "agradecimientos especiales")
ESPERADO(texto_creditos, 53, "yasuhiro sakai")
ESPERADO(texto_creditos, 54, "yoshitaka nishikawa")
ESPERADO(texto_creditos, 55, "hideki fujii")
ESPERADO(texto_creditos, 56, "yusuke nakano")
ESPERADO(texto_creditos, 57, "wataru yamaguchi")
ESPERADO(texto_creditos, 58, "phil sandhop")
ESPERADO(texto_creditos, 59, "super mario club")
ESPERADO(texto_creditos, 60, "modelo 3d de donkey kong por cortesía de rare u.k.")
ESPERADO(texto_creditos, 61, "fin")
ESPERADO(texto_creditos, 62, "equipo de mario kart 64")

// Intro de la batalla, avisos y banner del fantasma
ESPERADO(introduccion_batalla_texto, 0, "MODO BATALLA")
ESPERADO(introduccion_batalla_texto, 1, "¡REVIENTA LOS GLOBOS RIVALES!")
ESPERADO(introduccion_batalla_texto, 2, "SI PIERDES LOS 3, ¡QUEDAS FUERA!")
ESPERADO(mando_sin_texto, 0, "CONECTA UN MANDO AL PUERTO 1")
ESPERADO(mando_sin_texto, 1, "Y VUELVE A ENCENDER LA CONSOLA.")
ESPERADO(texto_menu_anuncio_fantasma, 0, "¡YA PUEDES RETAR AL FANTASMA!")

// Fuente de depuracion (solo ASCII, sin tildes)
ESPERADO(nombres_personaje_depuracion, 0, "MARIO")
ESPERADO(nombres_personaje_depuracion, 1, "LUIGI")
ESPERADO(nombres_personaje_depuracion, 2, "YOSHI")
ESPERADO(nombres_personaje_depuracion, 3, "TOAD")
ESPERADO(nombres_personaje_depuracion, 4, "DK")
ESPERADO(nombres_personaje_depuracion, 5, "WARIO")
ESPERADO(nombres_personaje_depuracion, 6, "PEACH")
ESPERADO(nombres_personaje_depuracion, 7, "BOWSER")
ESPERADO(depuracion_pantalla_modo_nombres, 0, "1 jug")
ESPERADO(depuracion_pantalla_modo_nombres, 1, "2 jug arr/abj")
ESPERADO(depuracion_pantalla_modo_nombres, 2, "2 jug izq/der")
ESPERADO(depuracion_pantalla_modo_nombres, 3, "3 jug")
ESPERADO(depuracion_pantalla_modo_nombres, 4, "4 jug")
ESPERADO(depuracion_sonido_modo_nombres, 0, "estereo")
ESPERADO(depuracion_sonido_modo_nombres, 1, "auriculares")
ESPERADO(depuracion_sonido_modo_nombres, 2, "xxx")
ESPERADO(depuracion_sonido_modo_nombres, 3, "mono")
ESPERADO(textos_menu_depuracion, 0, "depuracion")
ESPERADO(textos_menu_depuracion, 1, "si")
ESPERADO(textos_menu_depuracion, 2, "no")
ESPERADO(textos_menu_depuracion, 3, "num_pista")
ESPERADO(textos_menu_depuracion, 4, "pantalla")
ESPERADO(textos_menu_depuracion, 5, "jugador")
ESPERADO(textos_menu_depuracion, 6, "sonido")
ESPERADO(textos_menu_depuracion, 7, "cuadrado: copas de oro")
ESPERADO(nombres_circuito_depuracion, 0, "c mario")
ESPERADO(nombres_circuito_depuracion, 1, "choco")
ESPERADO(nombres_circuito_depuracion, 2, "castillo")
ESPERADO(nombres_circuito_depuracion, 3, "fantasma")
ESPERADO(nombres_circuito_depuracion, 4, "laberinto")
ESPERADO(nombres_circuito_depuracion, 5, "nieve")
ESPERADO(nombres_circuito_depuracion, 6, "playa")
ESPERADO(nombres_circuito_depuracion, 7, "c real")
ESPERADO(nombres_circuito_depuracion, 8, "c luigi")
ESPERADO(nombres_circuito_depuracion, 9, "granja")
ESPERADO(nombres_circuito_depuracion, 10, "autopista")
ESPERADO(nombres_circuito_depuracion, 11, "desierto")
ESPERADO(nombres_circuito_depuracion, 12, "sorbete")
ESPERADO(nombres_circuito_depuracion, 13, "arco iris")
ESPERADO(nombres_circuito_depuracion, 14, "estadio")
ESPERADO(nombres_circuito_depuracion, 15, "bloques")
ESPERADO(nombres_circuito_depuracion, 16, "edificio")
ESPERADO(nombres_circuito_depuracion, 17, "cubierta")
ESPERADO(nombres_circuito_depuracion, 18, "jungla")
ESPERADO(nombres_circuito_depuracion, 19, "donut")
