// Texto esperado de cada entrada de las tablas traducidas (estado ES en
// prueba_textos_tablas.inc.c): ESPERADO(tabla, indice, "texto").
// Esta en UTF-8 como el codigo; el Makefile lo pasa a EUC-JP con el mismo
// conversor que el build, asi que la comparacion es byte a byte.

// Personajes: nombres propios, iguales en espanol
ESPERADO(dato_800E76A8, 0, "MARIO")
ESPERADO(dato_800E76A8, 1, "LUIGI")
ESPERADO(dato_800E76A8, 2, "YOSHI")
ESPERADO(dato_800E76A8, 3, "TOAD")
ESPERADO(dato_800E76A8, 4, "D.K.")
ESPERADO(dato_800E76A8, 5, "WARIO")
ESPERADO(dato_800E76A8, 6, "PEACH")
ESPERADO(dato_800E76A8, 7, "BOWSER")
ESPERADO(dato_800E76A8, 8, "ーーーー")

// Longitud de cada pista en metros
ESPERADO(longitudes_circuito, 0, "567m")
ESPERADO(longitudes_circuito, 1, "687m")
ESPERADO(longitudes_circuito, 2, "777m")
ESPERADO(longitudes_circuito, 3, "747m")
ESPERADO(longitudes_circuito, 4, "772m")
ESPERADO(longitudes_circuito, 5, "734m")
ESPERADO(longitudes_circuito, 6, "691m")
ESPERADO(longitudes_circuito, 7, "1025m")
ESPERADO(longitudes_circuito, 8, "717m")
ESPERADO(longitudes_circuito, 9, "527m")
ESPERADO(longitudes_circuito, 10, "1036m")
ESPERADO(longitudes_circuito, 11, "753m")
ESPERADO(longitudes_circuito, 12, "756m")
ESPERADO(longitudes_circuito, 13, "2000m")
ESPERADO(longitudes_circuito, 14, "1591m")
ESPERADO(longitudes_circuito, 15, "")
ESPERADO(longitudes_circuito, 16, "")
ESPERADO(longitudes_circuito, 17, "")
ESPERADO(longitudes_circuito, 18, "893m")
ESPERADO(longitudes_circuito, 19, "")

// Opciones
ESPERADO(menu_opcion_texto, 0, "VOLVER AL MENÚ PRINCIPAL")
ESPERADO(menu_opcion_texto, 1, "SONIDO")
ESPERADO(menu_opcion_texto, 2, "COPIAR FANTASMAS")
ESPERADO(menu_opcion_texto, 3, "BORRAR TODOS LOS DATOS")
ESPERADO(sonido_nombres_modo, 0, "ESTÉREO")
ESPERADO(sonido_nombres_modo, 1, "AURICULARES")
ESPERADO(sonido_nombres_modo, 2, "")
ESPERADO(sonido_nombres_modo, 3, "MONO")
ESPERADO(dato_800E7878, 0, "SE BORRARÁN TODOS LOS")
ESPERADO(dato_800E7878, 1, "DATOS PARA SIEMPRE.")
ESPERADO(dato_800E7878, 2, "¿QUIERES CONTINUAR?")
ESPERADO(dato_800E7884, 0, "")
ESPERADO(dato_800E7884, 1, "SE HAN BORRADO")
ESPERADO(dato_800E7884, 2, "TODOS LOS DATOS.")

// Datos de las pistas
ESPERADO(datos_menu_texto, 0, "CRUZ*VER DATOS  CUADRADO*SALIR")
ESPERADO(distancia_texto, 0, "LONGITUD")
ESPERADO(opcion_menu_texto, 0, "VOLVER AL MENÚ")
ESPERADO(opcion_menu_texto, 1, "BORRAR RÉCORDS DE LA PISTA")
ESPERADO(opcion_menu_texto, 2, "BORRAR FANTASMA DE LA PISTA")
ESPERADO(dato_800E7840, 0, "SALIR")
ESPERADO(dato_800E7840, 1, "BORRAR")
ESPERADO(borrar_mejor_fantasma_texto, 0, "SE BORRARÁN LOS RÉCORDS")
ESPERADO(borrar_mejor_fantasma_texto, 1, "Y LA MEJOR VUELTA DE")
ESPERADO(borrar_mejor_fantasma_texto, 2, "ESTA PISTA. ¿DE ACUERDO?")
ESPERADO(borrar_mejor_fantasma_texto, 3, "SE BORRARÁ EL FANTASMA")
ESPERADO(borrar_mejor_fantasma_texto, 4, "DE ESTA PISTA.")
ESPERADO(borrar_mejor_fantasma_texto, 5, "¿DE ACUERDO?")
ESPERADO(dato_800E7860, 0, "NO SE PUEDE BORRAR")
ESPERADO(dato_800E7860, 1, "EL FANTASMA")
