#ifndef RECURSOS_PISTAS_CHOCO_MOUNTAIN_DATOS_PISTA_H
#define RECURSOS_PISTAS_CHOCO_MOUNTAIN_DATOS_PISTA_H

#include <ultra64.h>
#include <PR/gbi.h>
#include <juego/tipos_actores.h>
#include <juego/camino.h>
#include <juego/pista.h>

extern Gfx d_circuito_choco_mountain_dl_0[];
extern Gfx d_circuito_choco_montania_dl_B0[];
extern Gfx d_circuito_choco_mountain_dl_150[];
extern Gfx d_circuito_choco_mountain_dl_208[];
extern Gfx d_circuito_choco_montania_dl_2A8[];
extern Gfx d_circuito_choco_mountain_dl_330[];
extern Gfx d_circuito_choco_mountain_dl_410[];
extern Gfx d_circuito_choco_montania_dl_4D8[];
extern Gfx d_circuito_choco_mountain_dl_588[];
extern Gfx d_circuito_choco_mountain_dl_618[];
extern Gfx d_circuito_choco_montania_dl_6C0[];
extern Gfx d_circuito_choco_mountain_dl_750[];
extern Gfx d_circuito_choco_montania_dl_7E8[];
extern Gfx d_circuito_choco_mountain_dl_878[];
extern Gfx d_circuito_choco_mountain_dl_908[];
extern Gfx d_circuito_choco_mountain_dl_990[];
extern Gfx d_circuito_choco_montania_dl_A28[];
extern Gfx d_circuito_choco_montania_dl_B10[];
extern Gfx d_circuito_choco_montania_dl_BB8[];
extern Gfx d_circuito_choco_montania_dl_C40[];
extern Gfx d_circuito_choco_montania_dl_D30[];
extern Gfx d_circuito_choco_montania_dl_DF8[];
extern Gfx d_circuito_choco_montania_dl_EA0[];
extern Gfx d_circuito_choco_montania_dl_F38[];
extern Gfx d_circuito_choco_mountain_dl_1000[];
extern Gfx d_circuito_choco_montania_dl_10A8[];
extern Gfx d_circuito_choco_mountain_dl_1150[];
extern Gfx d_circuito_choco_montania_dl_11D8[];
extern Gfx d_circuito_choco_mountain_dl_1280[];
extern Gfx d_circuito_choco_mountain_dl_1330[];
extern Gfx d_circuito_choco_montania_dl_13E0[];
extern Gfx d_circuito_choco_mountain_dl_1488[];
extern Gfx d_circuito_choco_mountain_dl_1528[];
extern Gfx d_circuito_choco_montania_dl_15E8[];
extern Gfx d_circuito_choco_montania_dl_16B8[];
extern Gfx d_circuito_choco_mountain_dl_1788[];
extern Gfx d_circuito_choco_mountain_dl_1810[];
extern Gfx d_circuito_choco_montania_dl_18B8[];
extern Gfx d_circuito_choco_mountain_dl_1970[];
extern Gfx d_circuito_choco_montania_dl_1A40[];
extern Gfx d_circuito_choco_montania_dl_1AC8[];
extern Gfx d_circuito_choco_montania_dl_1B70[];
extern Gfx d_circuito_choco_montania_dl_1C18[];
extern Gfx d_circuito_choco_montania_dl_1CC8[];
extern Gfx d_circuito_choco_montania_dl_1D50[];
extern Gfx d_circuito_choco_montania_dl_1E08[];
extern Gfx d_circuito_choco_montania_dl_1E98[];
extern Gfx d_circuito_choco_montania_dl_1F40[];
extern Gfx d_circuito_choco_montania_dl_1FE0[];
extern Gfx d_circuito_choco_montania_dl_20C8[];
extern Gfx d_circuito_choco_mountain_dl_2168[];
extern Gfx d_circuito_choco_mountain_dl_2228[];
extern Gfx d_circuito_choco_montania_dl_22D8[];
extern Gfx d_circuito_choco_montania_dl_23C8[];
extern Gfx d_circuito_choco_mountain_dl_2468[];
extern Gfx d_circuito_choco_mountain_dl_2538[];
extern Gfx d_circuito_choco_mountain_dl_2600[];
extern Gfx d_circuito_choco_montania_dl_26D8[];
extern Gfx d_circuito_choco_mountain_dl_2780[];
extern Gfx d_circuito_choco_mountain_dl_2840[];
extern Gfx d_circuito_choco_mountain_dl_2908[];
extern Gfx d_circuito_choco_montania_dl_29B8[];
extern Gfx d_circuito_choco_montania_dl_2A88[];
extern Gfx d_circuito_choco_montania_dl_2B38[];
extern Gfx d_circuito_choco_montania_dl_2C08[];
extern Gfx d_circuito_choco_montania_dl_2C98[];
extern Gfx d_circuito_choco_montania_dl_2D50[];
extern Gfx d_circuito_choco_montania_dl_2DE8[];
extern Gfx d_circuito_choco_montania_dl_2EA0[];
extern Gfx d_circuito_choco_montania_dl_2F28[];
extern Gfx d_circuito_choco_montania_dl_2FD0[];
extern Gfx d_circuito_choco_mountain_dl_3070[];
extern Gfx d_circuito_choco_mountain_dl_3120[];
extern Gfx d_circuito_choco_montania_dl_31D8[];
extern Gfx d_circuito_choco_montania_dl_32B0[];
extern Gfx d_circuito_choco_mountain_dl_3368[];
extern Gfx d_circuito_choco_mountain_dl_3438[];
extern Gfx d_circuito_choco_mountain_dl_3550[];
extern Gfx d_circuito_choco_mountain_dl_3618[];
extern Gfx d_circuito_choco_montania_dl_36F0[];
extern Gfx d_circuito_choco_montania_dl_37D0[];
extern Gfx d_circuito_choco_montania_dl_38E8[];
extern Gfx d_circuito_choco_montania_dl_39A8[];
extern Gfx d_circuito_choco_montania_dl_3A80[];
extern Gfx d_circuito_choco_montania_dl_3B60[];
extern Gfx d_circuito_choco_montania_dl_3C18[];
extern Gfx d_circuito_choco_montania_dl_3CB8[];
extern Gfx d_circuito_choco_montania_dl_3D70[];
extern Gfx d_circuito_choco_montania_dl_3E18[];
extern Gfx d_circuito_choco_montania_dl_3EE0[];
extern Gfx d_circuito_choco_montania_dl_3FA8[];
extern Gfx d_circuito_choco_mountain_dl_4090[];
extern Gfx d_circuito_choco_mountain_dl_4138[];
extern Gfx d_circuito_choco_montania_dl_41F8[];
extern Gfx d_circuito_choco_montania_dl_42C8[];
extern Gfx d_circuito_choco_montania_dl_43C8[];
extern PuntoCaminoPista d_circuito_choco_mountain_camino_desconocido[];
extern PuntoCaminoPista d_circuito_choco_mountain_camino_pista[];
extern Lights1 d_circuito_choco_mountain_luz;
extern Vtx d_circuito_choco_montania_6005AF8[];
extern u8 d_circuito_choco_mountain_textura_pared[];
extern u8 d_circuito_choco_mountain_textura_roca[];
extern Vtx d_circuito_choco_mountain_modelo_roca_cayendo[];
extern Vtx d_circuito_choco_montania_6006C28[];
extern Vtx d_circuito_choco_montania_6006C78[];
extern Vtx d_circuito_choco_montania_6006CC8[];
extern Vtx d_circuito_choco_montania_6006D08[];
extern Vtx d_circuito_choco_montania_6006DA8[];
extern Vtx d_circuito_choco_montania_6006E48[];
extern Vtx d_circuito_choco_montania_6006EC8[];
extern Gfx d_circuito_choco_montania_dl_6EF8[];
extern Gfx d_circuito_choco_montania_dl_6F48[];
extern Gfx d_circuito_choco_montania_dl_6F88[];
extern Gfx d_circuito_choco_mountain_roca_cayendo_dl[];
extern Gfx d_circuito_choco_montania_dl_71B8[];
extern struct DatosAparicionActor d_circuito_choco_mountain_apariciones_roca_cayendo[];
extern struct DatosAparicionActor d_circuito_choco_mountain_caja_item_apariciones[];
extern SeccionesPista d_circuito_choco_mountain_direccion[];

#endif
