#include <ultra64.h>
#include <juego/macros.h>
#include <PR/os.h>
#include <juego/mk64.h>
#include <juego/sonidos.h>
#include <juego/estructuras_comunes.h>
#include <juego/tipos_actores.h>
#include <juego/definiciones.h>
#include <PR/gbi.h>

#include "carrera/preparacion_carrera.h"
#include "sistema/bucle_principal.h"
#include "sistema/matematicas.h"
#include "memoria/memoria_carrera.h"
#include "carrera/actores_extendidos.h"
#include "carrera/actores.h"
#include "juego/camino.h"
#include "juego/macros.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "carrera/actualizar_objetos.h"
#include "carrera/efectos.h"
#include "carrera/colision.h"
#include "audio/externo.h"
#include <recursos/datos_comunes.h>
#include "recursos/pistas/todos_datos_pistas.h"
#include "sistema/bucle_principal.h"
#include "datos/otras_texturas.h"
#include "actores/actores_basicos.inc.c"
#include "actores/aparicion_actores.inc.c"
#include "actores/colision_actores.inc.c"