#include <ultra64.h>
#include <juego/macros.h>
#include <juego/definiciones.h>
#include <juego/decodificacion.h>
#include <juego/mk64.h>

#include "carrera/actualizar_objetos.h"
#include "sistema/bucle_principal.h"
#include "memoria/memoria_carrera.h"
#include "carrera/camara.h"
#include "sistema/matematicas.h"
#include "sistema/matematicas_2.h"
#include "graficos/dibujar_objetos.h"
#include "juego/objetos.h"
#include "juego/camino.h"
#include "carrera/preparacion_carrera.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "carrera/objetos_y_efectos.h"
#include "carrera/inicio_hud_y_objetos.h"
#include "carrera/utilidades_objetos.h"
#include <recursos/datos_comunes.h>
#include "audio/externo.h"
#include "juego/sonidos.h"
#include <carrera/actores.h>
#include "carrera/logica_carrera.h"
#include "carrera/colision.h"
#include "carrera/efectos.h"
#include "carrera/camara_espectador.h"
#include "menus/elementos_menu.h"
#include "ceremonia/actores_podio.h"
#include "recursos/pistas/todos_datos_pistas.h"
#include <recursos/datos_ceremonia.h>
#include "ceremonia/ceremonia_y_creditos.h"
#include "menus/menus.h"
#include "datos/otras_texturas.h"
#include "datos/vertices_jugadores_y_listas.h"
#include "memoria/memoria_carrera.h"
#include "actualizar_objetos/ventana_item_y_objetos.inc.c"
#include "actualizar_objetos/humo_tren_y_barco.inc.c"
#include "actualizar_objetos/llamas_humo_y_hojas.inc.c"
#include "actualizar_objetos/nubes_estrellas_y_lakitu.inc.c"
#include "actualizar_objetos/items_cheep_cheep_y_boos.inc.c"
#include "actualizar_objetos/murcielagos_y_basura.inc.c"
#include "actualizar_objetos/thwomps.inc.c"
#include "actualizar_objetos/topos_gaviotas_y_cangrejos.inc.c"
#include "actualizar_objetos/pinguinos_globos_y_neon.inc.c"