#include <ultra64.h>
#include <juego/macros.h>
#include <juego/definiciones.h>
#include <juego/mk64.h>
#include <juego/pista.h>

#include "carrera/control_jugador.h"
#include "carrera/preparacion_carrera.h"
#include "juego/atributos_kart.h"
#include "memoria/memoria_carrera.h"
#include "sistema/matematicas.h"
#include "graficos/dibujar_jugador.h"
#include "carrera/efectos.h"
#include "carrera/colision.h"
#include "juego/camino.h"
#include "audio/externo.h"
#include "carrera/fisica_superficie.h"
#include "sistema/bucle_principal.h"
#include "carrera/camara.h"
#include "carrera/aparicion_jugadores.h"
#include "carrera/objetos_y_efectos.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "juego/sonidos.h"
#include "control_jugador/tablas_cpu.inc.c"
#include "control_jugador/salto_y_derrape.inc.c"
#include "control_jugador/efectos_jugador.inc.c"
#include "control_jugador/movimiento_cpu.inc.c"
#include "control_jugador/aceleracion.inc.c"
#include "control_jugador/giro_y_derrape.inc.c"
#include "control_jugador/mandos_carrera.inc.c"