#include <ultra64.h>
#include <juego/macros.h>
#include <juego/decodificacion.h>
#include <juego/mk64.h>
#include <juego/definiciones.h>
#include <juego/sonidos.h>
#include "carrera/preparacion_carrera.h"
#include "sistema/matematicas.h"
#include "juego/atributos_kart.h"
#include "juego/camino.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "graficos/dibujar_jugador.h"
#include "carrera/control_jugador.h"
#include "graficos/dibujar_objetos.h"
#include "carrera/objetos_y_efectos.h"
#include "carrera/efectos.h"
#include "audio/externo.h"
#include "carrera/aparicion_jugadores.h"
#include "menus/elementos_menu.h"
#include <juego/pista.h>
#include "efectos/efectos_basicos.inc.c"
#include "efectos/rayo_estrella_y_rampas.inc.c"
#include "efectos/evitar_items.inc.c"