#include <ultra64.h>
#include <juego/macros.h>
#include <memoria/memoria_carrera.h>
#include <juego/definiciones.h>
#include <juego/mk64.h>

#include "carrera/preparacion_carrera.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "carrera/objetos_y_efectos.h"
#include "carrera/inicio_hud_y_objetos.h"
#include "carrera/utilidades_objetos.h"
#include "carrera/actualizar_objetos.h"
#include "juego/objetos.h"
#include "juego/kart_bomba.h"
#include "sistema/guardado.h"
#include <recursos/datos_comunes.h>
#include <juego/sonidos.h>
#include <juego/decodificacion.h>
#include "audio/externo.h"
#include "recursos/pistas/todos_datos_pistas.h"
#include "sistema/bucle_principal.h"
#include "menus/menus.h"
#include "datos/otras_texturas.h"
#include "graficos/dibujar_objetos.h"
#include "menus/elementos_menu.h"
#include "datos/vertices_jugadores_y_listas.h"
#include "carrera/efectos.h"
#include "inicio_hud_y_objetos/hud_y_cielo.inc.c"
#include "inicio_hud_y_objetos/objetos_pista_y_hud_jugadores.inc.c"