#include <ultra64.h>
#include <juego/macros.h>
#include <juego/estructuras_comunes.h>
#include <juego/definiciones.h>
#include <juego/sonidos.h>
#include <juego/mk64.h>
#include <juego/pista.h>

#include "carrera/camara.h"
#include "juego/camino.h"
#include "carrera/repeticiones.h"
#include "sistema/bucle_principal.h"
#include "carrera/preparacion_carrera.h"
#include "carrera/objetos_y_efectos.h"
#include "carrera/actualizar_objetos.h"
#include "menus/elementos_menu.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "carrera/aparicion_jugadores.h"
#include "audio/externo.h"
#include "carrera/logica_carrera.h"
#include "graficos/cielo_y_pantalla_dividida.h"
#include "sistema/matematicas_2.h"
#include "carrera/efectos.h"
#include "math.h"
#include "menus/menus.h"
#include "juego/ids_musica.h"
#include "logica_carrera/estado_carrera.inc.c"
#include "logica_carrera/fin_carrera_y_demo.inc.c"