#include <ultra64.h>
#include <juego/macros.h>
#include <PR/gbi.h>
#include <juego/mk64.h>
#include <juego/pista.h>

#include "carrera/camara.h"
#include "carrera/objetos_y_efectos.h"
#include "sistema/bucle_principal.h"
#include "carrera/actores.h"
#include "carrera/preparacion_carrera.h"
#include "memoria/memoria_carrera.h"
#include <juego/definiciones.h>
#include "sistema/matematicas.h"
#include "sistema/matematicas_2.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "graficos/dibujar_jugador.h"
#include "graficos/dibujar_objetos.h"
#include "carrera/inicio_hud_y_objetos.h"
#include "carrera/actualizar_objetos.h"
#include "carrera/utilidades_objetos.h"
#include "carrera/efectos.h"
#include <recursos/vertices_800E8700.h>
#include "graficos/cielo_y_pantalla_dividida.h"
#include <recursos/datos_comunes.h>
#include "audio/externo.h"
#include "juego/objetos.h"
#include "juego/kart_bomba.h"
#include "menus/menus.h"
#include "datos/otras_texturas.h"
#include "carrera/aparicion_jugadores.h"
#include "juego/sonidos.h"
#include "datos/vertices_jugadores_y_listas.h"
#include "objetos_y_efectos/dibujar_objetos_y_nieve.inc.c"
#include "objetos_y_efectos/hud_pantalla_dividida.inc.c"
#include "objetos_y_efectos/hud_animado.inc.c"
#include "objetos_y_efectos/particulas_jugador.inc.c"
#include "objetos_y_efectos/particulas_superficie.inc.c"
#include "objetos_y_efectos/particulas_derrape.inc.c"
#include "objetos_y_efectos/particulas_y_onomatopeyas.inc.c"
#include "objetos_y_efectos/globos_batalla.inc.c"