#ifndef JUEGO_DEFINICIONES_H
#define JUEGO_DEFINICIONES_H

#define OK 1
#define MALO 0

#if defined(GCC) || defined(DEBUG)
#define MODO_DEPURACION_ACTIVACION 1
#else
#define MODO_DEPURACION_ACTIVACION 0
#endif

#define DPAD_TODOS_MANTENIDO_Y_BOTONES_C \
    (U_JPAD | L_JPAD | R_JPAD | D_JPAD | U_CBUTTONS | L_CBUTTONS | R_CBUTTONS | D_CBUTTONS)
#define TODOS_BOTONES                                                                                                   \
    (A_BUTTON | B_BUTTON | L_TRIG | R_TRIG | Z_TRIG | START_BUTTON | U_JPAD | L_JPAD | R_JPAD | D_JPAD | U_CBUTTONS | \
     L_CBUTTONS | R_CBUTTONS | D_CBUTTONS)
#define BOTON_REPETICION_A (1 << 31)
#define BOTON_REPETICION_B (1 << 30)
#define TRIG_REPETICION_Z (1 << 29)
#define TRIG_REPETICION_R (1 << 28)

#define CONTADOR_FRAME_REPETICION 0xFF0000
#define REPETICION_LIMPIEZA_FRAME_CONTADOR (0xFFFFFFFF & ~CONTADOR_FRAME_REPETICION)
#define PALANCA_Y_REPETICION 0xFF00
#define PALANCA_X_REPETICION 0xFF
#define INCREMENTAR_FRAME_REPETICION 0x10000

#define ACTIVO_MODO_DEMO 1
#define INACTIVO_MODO_DEMO 0

#ifdef VERSION_EU
#define ITER_TEMPORIZADOR_CIRCUITO 0.020041665999999999
#ifdef AVOID_UB
#define circuito_temporizador_iter_f 0.020041665999999999f
#else
#define circuito_temporizador_iter_f 0.01666666f
#endif
#else
#define ITER_TEMPORIZADOR_CIRCUITO 0.01666666
#define circuito_temporizador_iter_f 0.01666666f
#endif

#define v_bl_ank_temporizador_iter 0.01666666

#define INACTIVO_JUGADOR 0
#define jugador_desconocido_0_x10 (1 << 4)
#define jugador_desconocido_0_x40 (1 << 6)
#define jugador_desconocido_0_x80 (1 << 7)
#define INVISIBLE_JUGADOR_O_BOMBA (1 << 8)
#define PREPARACION_JUGADOR (1 << 9)
#define DESCONOCIDO_JUGADOR (1 << 10)
#define MODO_CINEMATICA_JUGADOR (1 << 11)
#define CPU_JUGADOR (1 << 12)
#define SECUENCIA_INICIO_JUGADOR (1 << 13)
#define HUMANO_JUGADOR (1 << 14)
#define EXISTE_JUGADOR (1 << 15)

#define HUMANO_JUGADOR_Y_CPU EXISTE_JUGADOR | HUMANO_JUGADOR | CPU_JUGADOR | SECUENCIA_INICIO_JUGADOR

#define CERO_JUGADORES_SELECCIONADO 0
#define UN_JUGADORES_SELECCIONADO 1
#define DOS_JUGADORES_SELECCIONADO 2
#define TRES_JUGADORES_SELECCIONADO 3
#define CUATRO_JUGADORES_SELECCIONADO 4
#define SELECCIONADO_JUGADOR_DEFINES_TOTAL 5

enum IdJugador {
    NINGUNO_JUGADOR = -1,
    JUGADOR_UNO = 0,
    JUGADOR_DOS = 1,
    JUGADOR_TRES = 2,
    JUGADOR_CUATRO = 3,
    JUGADOR_CINCO = 4,
    JUGADOR_SEIS = 5,
    JUGADOR_SIETE = 6,
    JUGADOR_OCHO = 7
};

#define JUGADORES_NUM 8

#define MARIO_TAMANIO 0.75f
#define LUIGI_TAMANIO 0.75f
#define YOSHI_TAMANIO 0.75f
#define TOAD_TAMANIO 0.75f
#define DK_TAMANIO 0.75f
#define WARIO_TAMANIO 0.75f
#define PEACH_TAMANIO 0.75f
#define BOWSER_TAMANIO 0.75f

#define NUM_MAX_MENU_PRINCIPAL_TIPOS_JUEGO 3

#define GRAN_PREMIO 0
#define CONTRARRELOJ 1
#define VERSUS 2
#define BATALLA 3

#define CC_50 0
#define CC_100 1
#define CC_150 2
#define CC_EXTRA 3
#define BATALLA_CC 4

enum { COPA_HONGO, COPA_FLOR, COPA_ESTRELLA, COPA_ESPECIAL, COPA_BATALLA, COPAS_NUM };

#define CIRCUITOS_NUM_POR_COPA 4

enum { CIRCUITO_UNO, CIRCUITO_DOS, CIRCUITO_TRES, CIRCUITO_CUATRO };

#define MARIO 0
#define LUIGI 1
#define YOSHI 2
#define TOAD 3
#define DK 4
#define WARIO 5
#define PEACH 6
#define BOWSER 7

#define MENU_OPCIONES 5
#define MENU_DATOS 6
#define MENU_DATOS_CIRCUITO 7
#define LOGO_INTRO_MENU 8
#define CONTROLLER_PAK_MENU 9
#define MENU_INICIO 10
#define MENU_PRINCIPAL 11
#define MENU_SELECCION_PERSONAJE 12
#define MENU_SELECCION_CIRCUITO 13
#define DUPLICAR_CARRERA 14

#define MENU_INICIO_DESDE_ABANDONAR 0
#define MENU_PRINCIPAL_DESDE_ABANDONAR 1
#define MENU_SELECCION_JUGADOR_DESDE_ABANDONAR 2
#define MENU_SELECCION_CIRCUITO_DESDE_ABANDONAR 3
#define CARRERA 4
#define FINAL 5
#define SECUENCIA_CREDITOS 9

#define MODO_PANTALLA_1P 0
#define PANTALLA_MODO_2J_PANTALLA_DIVIDIDA_HORIZONTAL 1
#define PANTALLA_MODO_2J_PANTALLA_DIVIDIDA_VERTICAL 2
#define PANTALLA_DIVIDIDA_MODO_3J_4J_PANTALLA 3
#define MODOS_PANTALLA_NUM 4

#define CONTRARRELOJ_3LAP_REGISTRO_1 0
#define CONTRARRELOJ_3LAP_REGISTRO_2 1
#define CONTRARRELOJ_3LAP_REGISTRO_3 2
#define CONTRARRELOJ_3LAP_REGISTRO_4 3
#define CONTRARRELOJ_3LAP_REGISTRO_5 4
#define CONTRARRELOJ_1LAP_REGISTRO 5

enum COLOR_ID {
    AZUL_TEXTO,
    VERDE_TEXTO,
    TEXTO_ROJO,
    AMARILLO_TEXTO,
    TEXTO_AZUL_VERDE_ROJO_CICLO_1,
    TEXTO_AZUL_VERDE_ROJO_CICLO_2
};

#define SONIDO_ESTEREO 0
#define SONIDO_AURICULARES 1
#define SONIDO_SIN_USO 2
#define SONIDO_MONO 3
#define MODOS_SONIDO_NUM 4

#define DEMO_UNO 0
#define DEMO_DOS 1
#define DEMO_TRES 2
#define DEMO_CUATRO 3
#define DEMO_CINCO 4
#define DEMO_SEIS 5
#define NUM_DEMOS 6

enum ITEMS {
     NINGUNO_ITEM = 0,
     ITEM_BANANA,
     GRUPO_BANANA_ITEM,
     ITEM_CAPARAZON_VERDE,
     TRIPLE_ITEM_CAPARAZON_VERDE,
     ITEM_CAPARAZON_ROJO,
     TRIPLE_ITEM_CAPARAZON_ROJO,
     AZUL_ITEM_CAPARAZON_ESPINOSO,
     RAYO_ITEM,
     ITEM_CAJA_ITEM_FALSA,
     ESTRELLA_ITEM,
     ITEM_BOO,
     HONGO_ITEM,
     HONGO_DOBLE_ITEM,
     ITEM_TRIPLE_HONGO,
     ITEM_SUPER_HONGO
};

enum COMPORTAMIENTOS_CPU {
    NINGUNO_COMPORTAMIENTO = 0,
    COMPORTAMIENTO_1,
    SALTO_COMPORTAMIENTO,
    CENTRO_CONDUCIR_COMPORTAMIENTO,
    IZQUIERDA_CONDUCIR_COMPORTAMIENTO,
    EXTERIOR_CONDUCIR_COMPORTAMIENTO,
    COMPORTAMIENTO_NORMAL_RAPIDEZ,
    COMPORTAMIENTO_RAPIDO_RAPIDEZ,
    COMPORTAMIENTO_LENTO_RAPIDEZ,
    COMPORTAMIENTO_9,
    COMPORTAMIENTO_10,
    COMPORTAMIENTO_MAX_RAPIDEZ
};

enum SENTIDO { NORTE, ESTE, SUR, OESTE };

enum LUGAR { PRIMER_LUGAR, SEGUNDO_LUGAR, TERCER_LUGAR, CUARTO_LUGAR };

#define IDO_SITUACION_GLOBO 0
#define PRESENTE_SITUACION_GLOBO 1
#define PARTIENDO_SITUACION_GLOBO 2

#define TIEMPO_MAX 0x927C0

#define GRADOS(grado) ((u16) (grado * 65536.0f / 360.0f))

#define TOCAR_BICHO 0x2
#define PORTON_TOCAR_BICHO 0x4
#define TROMPO_INSTANTE 0x40

#define BAJO_OOB_O_NIVEL_FLUIDO 0x1
#define OOB_PASADA_O_NIVEL_FLUIDO 0x2
#define BAJO_NIVEL_FLUIDO 0x4
#define BAJO_NIVEL_OOB 0x8

#define ANIMACION_CAMBIANDO 0x1
#define desconocido_002_desconocido_0_x2 0x2
#define desconocido_002_desconocido_0_x4 0x4
#define LADO_DE_KART 0x8

#define SILBATO 0x20
#define ERROR_ 0x40
#define WHIRRR 0x80
#define POOMP 0x100
#define BOING 0x800
#define EXPLOSION 0x1000

#define LAKITU_RECUPERACION 0x1
#define MANTENIDO_POR_LAKITU   0x2
#define LAKITU_APAGAR    0x4
#define LAKITU_ESCENA     0x8
#define EFECTO_HELADO   0x10
#define EFECTO_DESHIELO  0x20
#define EFECTO_CONGELADO   0x80
#define WENT_SOBRE_OOB  0x100
#define LAKITU_LAVA   0x1000
#define LAKITU_AGUA  0x2000

#define ARRIBA_ATRAS               0x1
#define GIRO_DERECHA            0x2
#define GIRO_IZQUIERDA             0x4
#define HACIA_ATRAS_MOVIMIENTO        0x8
#define CARRERA_GP_PERDER         0x10
#define ACELERADOR             0x20
#define DERECHA_TROMPO_TEMPRANO  0x40
#define IZQUIERDA_TROMPO_TEMPRANO   0x80
#define ACELERADOR_VUELCO_PUBLICAR     0x100
#define INVISIBLE_VOLVERSE    0x200
#define sin_uso_0_x_400        0x400
#define sin_uso_0_x_800        0x800
#define sin_uso_0_x_1000      0x1000
#define sin_uso_0_x_2000      0x2000
#define CONDUCIENDO_CERCA_TROMPO 0x4000
#define VARIABLE_BATALLA_DESCONOCIDO 0x8000

#define DISPARADOR_BANANA_GOLPE              0x1
#define DISPARADOR_VUELCO_ALTO             0x2
#define DISPARADOR_VUELCO_BAJO              0x4
#define DISPARADOR_TROMPO_CONDUCIENDO        0x80
#define THWOMP_DISPARADOR_APLASTAMIENTO         0x100
#define DISPARADOR_HONGO                0x200
#define BOO_DISPARADOR                   0x800
#define sin_uso_disparador_0_x_1000        0x1000
#define DISPARADOR_ESTRELLA                 0x2000
#define DISPARADOR_GOLPE_RAYO     0x4000
#define IMPULSO_RAMPA_MADERA_DISPARADOR      0x8000
#define sin_uso_disparador_0_x_20000      0x20000
#define EFECTO_ITEM_ARRASTRE            0x40000
#define GOLPE_PALETA_BARCO_DISPARADOR     0x80000
#define sin_uso_disparador_0_x_10000     0x100000
#define DISPARADOR_TROMPO            0x200000
#define DISPARADOR_VUELCO_VERTICAL    0x400000
#define IMPULSO_RAMPA_ASFALTO_DISPARADOR 0x800000
#define GOLPE_POR_DISPARADOR_ESTRELLA       0x1000000
#define DISPARADOR_IMPULSO_INICIO       0x2000000
#define EFECTO_BATALLA_PERDER        0x4000000
#define EFECTO_BOMBA_VOLVERSE        0x8000000
#define DISPARADOR_TROMPO_INICIO    0x10000000

#define TODOS_DISPARADORES (0xFFFFFFFF)
#define DISPARADORES_TROMPO_CARRERA (DISPARADOR_TROMPO | DISPARADOR_TROMPO_CONDUCIENDO | DISPARADOR_BANANA_GOLPE)
#define DISPARADORES_IMPULSO_RAMPA (IMPULSO_RAMPA_ASFALTO_DISPARADOR | IMPULSO_RAMPA_MADERA_DISPARADOR)
#define CUALQUIER_DISPARADORES_IMPULSO (DISPARADORES_IMPULSO_RAMPA | DISPARADOR_HONGO)
#define DISPARADORES_TRANSICION_ESTADO \
    (DISPARADOR_ESTRELLA | BOO_DISPARADOR | sin_uso_disparador_0_x_1000 | sin_uso_disparador_0_x_20000)
#define DISPARADORES_GOLPE                                                                                 \
    (GOLPE_POR_DISPARADOR_ESTRELLA | DISPARADOR_VUELCO_VERTICAL | DISPARADOR_GOLPE_RAYO | DISPARADOR_VUELCO_BAJO | \
     DISPARADOR_VUELCO_ALTO | THWOMP_DISPARADOR_APLASTAMIENTO)

#define EFECTO_FRENADO                   0x1
#define EFECTO_SALTO                       0x2
#define IMPULSO_RAMPA_MADERA_EFECTO           0x4
#define EFECTO_EN_EL_AIRE                    0x8
#define EFECTO_DERRAPANDO                 0x10
#define EFECTO_GIRO_AB                  0x20
#define EFECTO_TROMPO_CONDUCIENDO          0x40
#define EFECTO_TROMPO_BANANA           0x80
#define MINI_EFECTO_TURBO              0x100
#define EFECTO_ESTRELLA                    0x200
#define GOLPE_POR_CAPARAZON_VERDE_EFECTO      0x400
#define BANANA_CERCA_EFECTO_TROMPO     0x800
#define EFECTO_CARRERA_PERDIDO              0x1000
#define EFECTO_HONGO               0x2000
#define TEMPRANO_INICIO_TROMPO_EFECTO    0x4000
#define EFECTO_GOLPE_ENEMIGO             0x8000
#define EFECTO_VUELCO_TERRENO        0x10000
#define EFECTO_GOLPE_RAYO      0x20000
#define BANANA_TROMPO_GUARDADO_EFECTO   0x40000
#define desconocido_efecto_0_x_80000       0x80000
#define IMPULSO_RAMPA_ASFALTO_EFECTO   0x100000
#define EFECTO_RAPIDO_CPU             0x200000
#define EFECTO_REVERSA              0x400000
#define desconocido_efecto_0_x_800000     0x800000
#define EFECTO_ERROR_EXPLOSION     0x1000000
#define GOLPE_POR_EFECTO_ESTRELLA         0x2000000
#define EFECTO_APLASTAMIENTO              0x4000000
#define EFECTO_APLASTAMIENTO_PUBLICAR         0x8000000
#define desconocido_efecto_0_x_10000000 0x10000000
#define EFECTO_FUERA_DERRAPE      0x20000000
#define EFECTO_RAYO          0x40000000
#define BOO_EFECTO                0x80000000
#define TODOS_EFECTOS               0xFFFFFFFF

#define DURACION_EFECTO_ESTRELLA 0xA
#define BOO_DURACION_EFECTO 0x7

#define ALPHA_MAX 0xFF
#define ALPHA_MIN 0x0
#define ALPHA_BOO_EFECTO 0x60

#define CAPARAZON_PRIMER_APARICION 0
#define CAPARAZON_SEGUNDO_APARICION 1
#define CAPARAZON_TERCER_APARICION 2

#define GPACK_RGB888(r, g, b) (((r) << 16) | ((g) << 8) | (b))
#define LUZ_COLOR GPACK_RGB888(0x1C, 0x00, 0x00)
#define COLOR_LAVA GPACK_RGB888(0x34, 0x00, 0x00)
#define NEGRO_COLOR GPACK_RGB888(0, 0, 0)

#endif

#define TAMANIO_CUADRICULA 32

#define EJE_MIRANDO_Y 0x4000
#define EJE_MIRANDO_X 0x8000
#define EJE_MIRANDO_Z 0x2000

#define NINGUNO_CARRERA 0
#define PREP_CARRERA 1
#define PREPARACION_CARRERA 2
#define CARRERA_EN_PROGRESO 3
#define CARRERA_HUMANO_TERMINADO 4
#define HECHO_CARRERA 5
#define ABANDONANDO_CARRERA 6
#define RESULTADOS_CUADRANTE_CARRERA 7
