#ifndef JUEGO_IDS_MUSICA_H
#define JUEGO_IDS_MUSICA_H

enum SecId {
    SEC_SONIDO_JUGADOR,
    SEC_PANTALLA_TITULO_MENU,
    SEC_MENU_MENU_PRINCIPAL,
    SEC_RACEWAY_PISTA,
    SEC_FARM_PISTA,
    SEC_MONTANIA_PISTA,
    SEC_BEACH_PISTA,
    SEC_ATERRADOR_PISTA,
    SEC_NIEVE_PISTA,
    SEC_CASTILLO_PISTA,
    SEC_DESIERTO_PISTA,
    SEC_INICIAL_CARRERA_EVENTO,
    SEC_EVENTO_CARRERA_FINAL_VUELTA,
    SEC_EVENTO_CARRERA_META_PRIMER,
    SEC_EVENTO_CARRERA_META_OTRO,
    SEC_EVENTO_CARRERA_META_PERDER,
    SEC_MENU_RESULTADOS_PANTALLA_VICTORIA,
    SEC_EVENTO_CARRERA_POTENCIADOR_ESTRELLA,
    SEC_RAINBOW_PISTA,
    SEC_JUNGLE_PISTA,
    SEC_EVENTO_CEREMONIA_TROFEO_PERDER,
    SEC_TURNPIKE_PISTA,
    SEC_INICIAL_CARRERA_EVENTO_VS,
    SEC_MENU_RESULTADOS_PANTALLA_VICTORIA_VS,
    SEC_MENU_RESULTADOS_PANTALLA_PERDER,
    SEC_BATALLA_PISTA,
    SEC_EVENTO_CEREMONIA_PRESENTACION_PART1,
    SEC_EVENTO_CEREMONIA_PRESENTACION_PART2_VICTORIA,
    SEC_EVENTO_CEREMONIA_TROFEO_CREDITOS,
    SEC_EVENTO_CEREMONIA_PRESENTACION_PART2_PERDER,
	SEC_CANTIDAD
};

#endif
