#include <ultra64.h>
#include <juego/mk64.h>
#include <PR/gbi.h>
#include <juego/macros.h>
#include <juego/definiciones.h>
#include <juego/estructuras_comunes.h>
#include <juego/tipos_actores.h>
#include "carrera/camara.h"
#include "memoria/memoria_carrera.h"
#include "sistema/matematicas.h"
#include "sistema/matematicas_2.h"
#include "juego/objetos.h"
#include "juego/camino.h"
#include "juego/kart_bomba.h"
#include <recursos/datos_comunes.h>
#include "graficos/dibujar_jugador.h"
#include "carrera/animacion.h"
#include "carrera/ia_vehiculos_y_camara.h"
#include "carrera/objetos_y_efectos.h"
#include "carrera/inicio_hud_y_objetos.h"
#include "graficos/dibujar_objetos.h"
#include "carrera/actualizar_objetos.h"
#include "menus/elementos_menu.h"
#include "carrera/colision.h"
#include "sistema/bucle_principal.h"
#include "menus/menus.h"
#include "carrera/utilidades_objetos.h"
#include "carrera/preparacion_carrera.h"
#include <recursos/luces_800E45C0.h>
#include "recursos/pistas/todos_datos_pistas.h"
#include <juego/vehiculos.h>
#include "datos/vertices_jugadores_y_listas.h"
#include "dibujar_objetos/cargar_texturas.inc.c"
#include "dibujar_objetos/texturas_hud.inc.c"
#include "dibujar_objetos/ventana_item_y_minimapa.inc.c"
#include "dibujar_objetos/objetos_ambiente.inc.c"
#include "dibujar_objetos/objetos_animados.inc.c"
#include "dibujar_objetos/kart_bomba_y_depuracion.inc.c"