#include <ultra64.h>
#include <juego/macros.h>
#include <juego/segmentos.h>
#include <juego/estructuras_comunes.h>
#include "sistema/matematicas.h"
#include "ceremonia/ceremonia_y_creditos.h"
#include "carrera/preparacion_carrera.h"
#include "ceremonia/bucle_creditos.h"
#include "juego/objetos.h"
#include "sistema/bucle_principal.h"
#include "carrera/camara.h"
#include "audio/externo.h"
#include <juego/sonidos.h>
#include "ceremonia/actores_podio.h"
#include "menus/elementos_menu.h"
#include "carrera/objetos_y_efectos.h"
#include "juego/definiciones.h"
#include "juego/ids_musica.h"
#include "ceremonia_y_creditos/splines_y_vectores.inc.c"
#include "ceremonia_y_creditos/cinematica.inc.c"