#ifndef RECURSOS_PISTAS_TODOS_MODELOS_PISTAS_H
#define RECURSOS_PISTAS_TODOS_MODELOS_PISTAS_H

#include "juego/macros.h"
#include <juego/estructuras_comunes.h>

extern VtxCircuito d_circuito_big_donut_vertice[0x48D];
extern VtxCircuito d_circuito_block_fort_vertice[0x440];
extern VtxCircuito d_circuito_double_deck_vertice[0x22B];
extern VtxCircuito d_circuito_skyscraper_vertice[0x43E];
extern VtxCircuito d_circuito_choco_mountain_vertice[0x15B8];
extern VtxCircuito d_circuito_frappe_snowland_vertice[0x1599];
extern VtxCircuito d_circuito_mario_raceway_vertice[0x167D];
extern VtxCircuito d_circuito_toads_turnpike_vertice[0x18D7];
extern VtxCircuito d_circuito_kalimari_desert_vertice[0x18F9];
extern VtxCircuito d_circuito_koopa_troopa_beach_vertice[0x24A0];
extern VtxCircuito d_circuito_luigi_raceway_vertice[0x1730];
extern VtxCircuito d_circuito_moo_moo_farm_vertice[0x1F24];
extern VtxCircuito d_circuito_banshee_boardwalk_vertice[0x1351];
extern VtxCircuito d_circuito_dks_jungle_parkway_vertice[0x162F];
extern VtxCircuito d_circuito_rainbow_road_vertice[0xC27];
extern VtxCircuito d_circuito_yoshi_valley_vertice[0xE88];
extern VtxCircuito d_circuito_bowsers_castle_vertice[0x2537];
extern VtxCircuito d_circuito_royal_raceway_vertice[0x2072];
extern VtxCircuito d_circuito_sherbet_land_vertice[0xA76];
extern VtxCircuito d_circuito_wario_stadium_vertice[0x17B3];

#define d_circuito_big_donut_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_big_donut_vertice)
#define d_circuito_block_fort_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_block_fort_vertice)
#define d_circuito_double_deck_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_double_deck_vertice)
#define d_circuito_skyscraper_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_skyscraper_vertice)
#define d_circuito_choco_mountain_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_choco_mountain_vertice)
#define d_circuito_frappe_snowland_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_frappe_snowland_vertice)
#define d_circuito_mario_raceway_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_mario_raceway_vertice)
#define d_circuito_toads_turnpike_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_toads_turnpike_vertice)
#define d_circuito_kalimari_desert_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_kalimari_desert_vertice)
#define d_circuito_koopa_troopa_beach_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_koopa_troopa_beach_vertice)
#define d_circuito_luigi_raceway_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_luigi_raceway_vertice)
#define d_circuito_moo_moo_farm_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_moo_moo_farm_vertice)
#define d_circuito_banshee_boardwalk_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_banshee_boardwalk_vertice)
#define d_circuito_dks_jungle_parkway_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_dks_jungle_parkway_vertice)
#define d_circuito_rainbow_road_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_rainbow_road_vertice)
#define d_circuito_yoshi_valley_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_yoshi_valley_vertice)
#define d_circuito_bowsers_castle_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_bowsers_castle_vertice)
#define d_circuito_royal_raceway_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_royal_raceway_vertice)
#define d_circuito_sherbet_land_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_sherbet_land_vertice)
#define d_circuito_wario_stadium_cantidad_vertice CANTIDAD_ARREGLO(d_circuito_wario_stadium_vertice)

#endif
